"""Enums for reconciliation system."""

from enum import Enum


class ReconciliationStatus(str, Enum):
    RECONCILED = "RECONCILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    MISSING_PAYMENT = "MISSING_PAYMENT"
    MISSING_BANK_TRANSACTION = "MISSING_BANK_TRANSACTION"
    DUPLICATE = "DUPLICATE"
    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    INVALID_DATA = "INVALID_DATA"
    UNMATCHED = "UNMATCHED"


class MatchType(str, Enum):
    EXACT_REFERENCE = "EXACT_REFERENCE"
    HIGH_CONFIDENCE_MULTI_SIGNAL = "HIGH_CONFIDENCE_MULTI_SIGNAL"
    MEDIUM_CONFIDENCE_FUZZY = "MEDIUM_CONFIDENCE_FUZZY"
    MANUAL_REVIEW_NEEDED = "MANUAL_REVIEW_NEEDED"
    UNMATCHED = "UNMATCHED"


class DataSourceType(str, Enum):
    INVOICES = "invoices"
    PAYMENTS = "payments"
    BANK_TRANSACTIONS = "bank_transactions"


class QualityIssueType(str, Enum):
    MISSING_PRIMARY_KEY = "MISSING_PRIMARY_KEY"
    MISSING_AMOUNT = "MISSING_AMOUNT"
    NEGATIVE_AMOUNT = "NEGATIVE_AMOUNT"
    INVALID_DATE = "INVALID_DATE"
    DUPLICATE_ID = "DUPLICATE_ID"
    MISSING_REQUIRED_COLUMN = "MISSING_REQUIRED_COLUMN"
